interface: eth1

# Modos de debug/teste
verbose_mode: true # modo verbose ativo/desativo
test_mode: true # Gera pacotes artificiais periodicamente
test_interval: 5 # Intervalo em segundos para pacotes artificiais

MODBUS_CLIENT:
  - 172.27.224.10

MODBUS_SERVER:
  - 172.27.224.250

rules_file: rules/modsentinel.rules
