interface: eth0
log_level: INFO

# Modos de debug/teste
verbose_mode: true # modo verbose ativo/desativo
test_mode: true # Gera pacotes artificiais periodicamente
test_interval: 5 # Intervalo em segundos para pacotes artificiais
