interface: eth2

MODBUS_CLIENT:
  - 172.27.224.10
  - 172.27.224.251

MODBUS_SERVER:
  - 172.27.224.250

# Lista de pares IP-MAC permitidos para deteção de ARP spoofing
allowed_macs:
  "172.27.224.10": "00:0c:29:64:ce:e3" # HMI
  "172.27.224.250": "00:0c:29:c1:c9:f4" # PLC 1
  "172.27.224.251": "00:0c:29:01:28:44" # PLC 2

# Endereço(s) IP de atacantes conhecidos (ex.: Kali Linux)
known_attackers:
  - 172.27.224.40
