interface: eth1
verbose_mode: true
test_mode: true
test_interval: 5

pcap_capture:
  enabled: true
  file: logs/capture.pcap

csv_logging:
  enabled: true
  file: logs/traffic.csv

MODBUS_CLIENT:
  - 172.27.224.10

MODBUS_SERVER:
  - 172.27.224.250

rules_file: rules/modsentinel.rules
